---
title: "MPAs and DPSAs"
author: "Dan Ovando"
date: "June 9, 2015"
output:
  pdf_document: default
  html_document: default
  word_document:
    fig_caption: yes
    fig_height: 4.5
    fig_width: 7.25
number_sections: yes
csl: canadian-journal-of-fisheries-and-aquatic-sciences.csl
bibliography: CCFRP Paper.bib
toc: no
---

## Discussion

* Issues etc (e.g. CPUE ratio is a problem early on)


# Lit Review

* Bentley & Stokes [-@Bentley2009]
    * We need to be thinking more about the management procedures themselves, and less focused on the assessment themselves
    * Using data signals to guide management
* Starr et al. [-@Starr2015] describe the hetergeneiety in 
    * They document hetergeneity in the effects of the reserves over time and that it takes a while to act
    * Rebuilding and sustaining exploited species is a specific goal of the California MLPA
    * Provides a thorough summary of ways in which we can use MPAs to track environmental changes over time
    * has a great table of movement rates for each of the species
    * Reserve effects may take a while to kick in, but information from the reserve starts to accrue immediately 
* McGillard et al. [-@McGilliard2014]
    * Focuses on use of density ratio
    * They basically make the case for using density ratios for management
    * They do point out that the density ratio is tough to use in it's early phases
    * However, you could still infer something form the separate signals;if fished density is going down in the reference site while unfished density is going down might be a sign to be cautious 
    
* Geromont & Butterwork [-@Geromont2014]
    * Data poor can work
    
* White Paper
    * We need more community based management
    
* Wilson et al. [-@Wilson2010]
    * You can use MPAs to guide management
    * Multi-indicator are good
* McGilliard et al. [-@McGilliard2014]
    * Accounting for spatial variation caused by reserves is important
* 

#The new pitch
* We need DLAs
* We need MPAs
* MPAs can inform DLAs
* Serve as our canary in the coalmine
* So, how do we think about using DLAs with MPAs?
* Methods
* Results
* Comparisons

#Title Page

#Abstract

Fisheries managers are often faced with the challenge of managing at a spatial scale that balances the inherent demographic and biological variability of the stock with the practical constraints of governance, available resources, and data. Many nearshore rockfish species in California exhibit marked differences in growth rates and reproductive patterns, and experience variable harvest pressure across space. However, management regulations are generally applied across broad geographic scales, failing to account for spatial differences in life history and fishing pressure, leading to areas of low and high depletion and ultimately a disenfranchised fishing community. We use a time series of fishery independent length and density data for nearshore California finfish collected inside and outside of no-take marine protected areas (MPAs) by the California Collaborative Fisheries Research Program to perform a series of data-limited assessments (DLAs) at a variety of spatial scales. These DLAs include both length and density based metrics of stock status. This analysis allows us to a) provide improved scientific guidance on the health of these stocks at local scales and b) evaluate spatial and temporal differences in stock status. We are also able to compare and contrast the results and trends produced by the different DLA methods, providing guidance for the concept of multi-indicator management. Our results indicate that it may be possible to use collaborative research and MPAs to provide fine-scale scientific guidance for management and quota-allocation using DLAs. This type of process could increase the feasibility of fisheries management that leverages DLAs, co-management, and collaborative science to better reflect the spatial diversity of the health of fished populations. 

#Introduction

* Why Care?
    * Fisheries management can work [@Hilborn2014]
    * But, the proven tools are designed for the data rich world, and much of the world is data poor. And in those places, things aren't working well [@Costello2012]
    * Many tools have been proposed to address this (lots of example citations). It is clear that there are ways in which we can use data-limited approaches, but there's a lack of research on the actual implementation of these methods
    * Where data-limited approached have been implemented, they have focused on catch-only methods. The US provides a clear example of this [@Berkson2015]. 
    * While catch-only methods have many useful qualities, they can be quite limited both in their performance and their applicability. So, we should explore other approaches
    * There have been MSE's
    * Or bently and stokes 
    * You try and count the fish in the sea, or you deceptively respond 
    * Garamont and butterworth 
    * Dowling 2008 applies it Australian fisheries 
    * MPA angle 
        * Here we apply some of these tried and true methods to see how we can use these conservation 
        * This is the first tangible evidence in California to support the use of MPAs in fisheries management
        * Let's start thinking about really leveraging the data
        * Here's the five things that I recommend 
        * Climate ready fisheries: How do you develop adaptive management institutions that respond to climate 
        change 
        * These MPAs provide a window into an unfished world: the canary in the coalmine 
    * Plug CCFRP/White paper 
    * Plug SNAP 
    * Reach out for slides etc. 
        
    
* The solution
    * Length and reserve based assessments have a grounding in the literature 
    * Length and reserve based assessments may be easier and more practical to collect for many communities. 
    * In addition, these methods can allow for fine-scale spatial management (matching scale of management paper) that may not be possible 
    * CCFRP provides a perfect example to evaluate the ability of length and reserve based data to provide useful data 
    * We use the CCFRP data to evaluate a series of DLAs
    
* Methods
    * CCFRP data
    * Assessment methods
    
#Results

1. Do assessments tell the same story?
2. Does and aggregate assessment tell the same as individual sites?
3. Is there the same story across species? 

* Case study
    * Pick one species and follow it through
    * Plot and Discussion of Density Ratio
    * Plot and discussion of F/M
    * Plot and discussion of SPR
    * What about spatial variation?
        * A graph that shows both the final value and the slope since the first year at each of the sites as a point for each metric?
        * Or a map?
* Across species
    * A sampling regime like this allows for evaluation of many species, especially useful in a data poor context that may not allow for individual management plans
    * Do we need multi-species?
    * Look at variability in current metrics/trend across species 
    * Identify outlive species etc. 

#Discussion

* Limitations
    * Selectivity
    * Spatial stuff
    * MPA SPR
* For a single species, do we see concurrence across methods that could guide management?
    * Density ratio poses a problem early on when the MPA is recovering: MPA recovers faster than fished area so density ratio goes down
    * Do we see concurrence from catch curve and LBSPR F/M?
    * How much spatial variability is there?
* For multiple species, do we see concurrence across species?
* What species fail? If so why? (e.g. ontogenetic shifts)
* Take Home
    * Programs like CCFRP can provide high resolution data that is very usable for management
    * Evidence that the data are useful and robust
    * But, whatever goes wrong in the results 
    * Strong evidence that properly designed programs like CCFRP, together with fishery independent data, could serve as a data-limited alternative to catch-only methods
    * Further research addressing MSE of these things will be useful
    
# Figures

1. A map of the CCFRP study area
2. Assessment summary for selected species
    * Density Trends
    * Catch curve and LBSPR F/M
    * SPR
3. Spatial variation for selected species
    * For each method, points showing the aggregate value and the individual site values
    * Or, a series of maps showing hetergeoneity of results. Might be better
4. Copy of 2, but with lines for each species. If that gets too confusing, can just do the most recent year
5. Some kind of graphical interpretation of multiple results by species: green yellow red depending on concurrence of metrics? Might be too much

# Tables

1. Life history values used
